# <font color=teal>Please Answer These Questions:</font>

**1. What does one need to do to use a module?**
> * _<font color=aqua>Use the IMPORT statement, for example, "import datetime".</font>_

**2. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.**
> * _<font color=aqua>import math  
print(math.sqrt(36))  
print(math.ceil(36.67))</font>_

**3. What is a benefit of using Exception handling?**
> * _<font color=aqua>A benefit to Exception handling is that it can test a block of code for errors and allow the code to continue running past the error(s).</font>_

**4. NumPy arrays are like what Python data type?**
> * _<font color=aqua>NumPy arrays are similar to Lists.</font>_

**5. What is one of the main benefits of using NumPy arrays.**
> * _<font color=aqua>A main benefit to using NumPy arrays: Uses less memory.</font>_

**6. What is one of the main requirements about the 'dtype' of NumPy arrays?**
> * _<font color=aqua>Data types MUST be the same.</font>_

**7. Of the 10 uses of NumPy, name 2.**
> * _<font color=aqua>(1) Searches, sorts and counts</font>_
> * _<font color=aqua>(2) Statistical operations</font>_

**8. Name one of the other libraries we will use with NumPy?**
> * _<font color=aqua>Panda</font>_

**9. What is the shape of NumPy arrays?**
> * _<font color=aqua>(dimension, length and size of each array)</font>_

**10. What is a Tensor?**
> * _<font color=aqua>An array with 3 or more dimensions.</font>_

*11. Name a reason why it is better using NumPy for Data Analysis than using a Python List?**
> * _<font color=aqua>Less memory and faster than Lists.</font>_

**12. When creating an "empty" array, where do the elements come from?**
> * _<font color=aqua>content is random and depends on state of the memory.</font>_

**13. What does Pandas stand for?**
> * _<font color=aqua>Panel Data</font>_

**14. What are the 2 collections used in Pandas?**
> * _<font color=aqua>(1) Series</font>_
> * _<font color=aqua>(2) DataFrames</font>_

**15. Name 4 things Pandas can do for us.**
> * _<font color=aqua>(1) Data Cleansing</font>_
> * _<font color=aqua>(2) Data Normalization</font>_
> * _<font color=aqua>(3) Data Visualization</font>_
> * _<font color=aqua>(4) Data Inspection</font>_

**16. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?**
> * _<font color=aqua>inplace = True</font>_

**17. What is a CSV**
> * _<font color=aqua>A file that contains plain text and most commonly separated by commas.</font>_

**18. When cleaning data what values do we not like in our data?**
> * _<font color=aqua>Null values</font>_


In [30]:
import math
print(math.sqrt(36))
print(math.ceil(36.67))

6.0
37


In [26]:
import numpy as np

# 1. Concatenate these 3 arrays into a new array named 'newArray'...
arrayA = np.array([[25, 16]])
arrayB = np.array([[11, 2], [13, 4]])
arrayC = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC))
print(newArray)

# 2. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\n", sortedArray)

# 3. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2,2,3)
print("\n", reshapedArray)

# 4. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
a, b = reshapedArray

a0, a1 = a
b0, b1 = b
print("\nUnpacked tuple into 4 variables...", a0)
print(a1)
print(b0)
print(b1)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

Unpacked tuple... [[16 25  2]
 [11  4 13]]
[[ 7 81  5]
 [ 6 11 12]]

Unpacked tuple into 4 variables... [16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]


In [15]:
# 5. Combine and sort the following arrays into one called 'comboArray' ...
import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate(((one, two, three)))
print(comboArray)


# 6. Take 'comboArray' and perform the following slicing activities:
        # print sec1 - the 2nd element
        # print sec2 - all elements from the 3rd element to the last
        # print sec3 - all elements from the 4th to the 14th elements
        # print sec4 - the last 6 elements
        # print sec5 - all element from #0 up to and including #15, using the negative number method, 
                # i.e. taking a section from the end.
        # print sec6 - from #20 every even element to the end
        # print sec7 - from the last element moving forward, every 5th element.

print("Number of Elements...", len(comboArray))
sec1 = comboArray[2]
print("sec1...", sec1)
sec2 = comboArray[3:24]
print("sec2...", sec2)
sec3 = comboArray[4:15]
print("sec3...", sec3)
sec4 = comboArray[-6:]
print("sec4...", sec4)
sec5 = comboArray[:-8]
print("sec5...", sec5)
sec6 = comboArray[20:25:2]
print("sec6...", sec6)
sec7 = comboArray[::-5]
print("sec7...", sec7)

[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
Number of Elements... 24
sec1... 12
sec2... [13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
sec3... [14 15 16 17 20 21 22 23 24 25 26]
sec4... [2 3 4 5 6 7]
sec5... [10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec6... [4 6]
sec7... [ 7  2 25 20 13]


In [24]:
# 7. Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
   
import numpy as np

Array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

Array2 = np.array([[17.0, 70.0, 10.7]])

Addition = np.add(Array1, Array2)
print("Addition: \n", Addition)

Division = np.divide(Array1, Array2)
print("\n Division: \n", Division)

Times = np.multiply(Array1, Array2)
print("\n Multiplication: \n", Times)


# 8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in point #7.

Subtraction = np.subtract(Array1, Array2)
print("\n Subtraction: \n", Subtraction)

# 9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.

Divisible1 = Array1[Array1 % 3 == 0]
print("\n Divisible by 3 for Array 1: \n", Divisible1)


Addition: 
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

 Division: 
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

 Multiplication: 
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

 Subtraction: 
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]

 Divisible by 3 for Array 1: 
 [ 0.  0. 30. 24. 15.]

 Divisible by 3 for Array 2: 
 []


In [32]:
# 10. Using Series, create a DataFrame that looks like this:

#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can

#Name: Dinner, dtype: object

import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name='Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name='Quantity')
Unit = pd.Series(["cups", "cup", "large", "can"], name='Unit')

index_labels = ["Item 1", "Item 2", "Item 3", "Item 4"]
Ingredients.index = index_labels
Quantity.index = index_labels
Unit.index = index_labels

Dinner = pd.concat([Ingredients,Quantity,Unit], axis=1)
print(Dinner)





       Ingredients  Quantity   Unit
Item 1       Flour         4   cups
Item 2        Milk         1    cup
Item 3        Eggs         2  large
Item 4        Spam         1    can


In [48]:
import pandas as pd

# 11. Take this data and create a DataFrame named studentData
data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(data)
print(studentData)

# 12. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData.insert(7, "Desserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], True)
print("\n", studentData)

# 13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ['Name'], inplace = True)
print("\n Sorted by Name: \n", studentData)

studentData.sort_values(by = ['address'], inplace = True)
print("\n Sorted by Address: \n", studentData)


      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  

 Sorted by Name: 
       Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   

In [71]:
import pandas as pd

# 14. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv', index=False)
df_saved_file = pd.read_csv('cows_and_goats.csv')


In [70]:
import pandas as pd

# 15. 
    # (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
    # (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

df = pd.DataFrame({'Green Veggies': ['zucchini', 'lettuce', 'cucumbers'], 'Yellow Veggies': ['potatoes', 'corn', 'onions']}, index=[1, 2, 3])

df.to_csv('veggies.csv', index=False)
df_saved_file = pd.read_csv('veggies.csv')

df1 = df.replace(to_replace={'lettuce': 'spinach'})
print(df1)

df1.to_csv('updatedveggies.csv', index=False)
df_saved_file = pd.read_csv('updatedveggies.csv')


  Green Veggies Yellow Veggies
1      zucchini       potatoes
2       spinach           corn
3     cucumbers         onions
